---
- name: Write swapfile
  command: |
    {% if swapfile_use_dd %}
    dd if=/dev/zero of={{ swapfile_location }} bs=1M count={{ swapfile_size }} creates={{ swapfile_location }}
    {% else %}
    fallocate -l {{ swapfile_size }} {{ swapfile_location }} creates={{ swapfile_location }}
    {% endif %}
  register: write_swapfile
  when: swapfile_size != false

- name: Set swapfile permissions
  file:
    path: "{{ swapfile_location }}"
    mode: 0600
  when: swapfile_size != false

- name: Create swapfile
  command: "mkswap {{ swapfile_location }}"
  register: create_swapfile
  when: swapfile_size != false and write_swapfile.changed
  tags:
    - skip_ansible_lint

- name: Enable swapfile
  command: "swapon {{ swapfile_location }}"
  when: swapfile_size != false and create_swapfile.changed and not ci_build
  tags:
    - skip_ansible_lint

- name: Add swapfile to /etc/fstab
  lineinfile:
    dest: /etc/fstab
    line: "{{ swapfile_location }}   none    swap    sw    0   0"
    state: present
  when: swapfile_size != false

- name: Configure vm.swappiness
  lineinfile:
    dest: /etc/sysctl.conf
    line: "vm.swappiness = {{ swapfile_swappiness }}"
    regexp: "^vm.swappiness[\\s]?="
    state: present
  notify: Reload sysctl
  when: swapfile_swappiness != false

- name: Configure vm.vfs_cache_pressure
  lineinfile:
    dest: /etc/sysctl.conf
    line: "vm.vfs_cache_pressure = {{ swapfile_vfs_cache_pressure }}"
    regexp: "^vm.vfs_cache_pressure[\\s]?="
    state: present
  notify: Reload sysctl
  when: swapfile_vfs_cache_pressure != false

- name: Install watch script
  copy:
    src: generateswapfile.sh
    dest: /usr/local/bin/generateswapfile
    mode: 0755

- name: Check if swap is enabled on boot
  lineinfile:
    line: "/usr/local/bin/generateswapfile {{ swapfile_location }} {{ swapfile_size }}"
    dest: /etc/rc.local
    insertbefore: 'exit 0'
  when: swapfile_check_swap_on_boot|bool == true
